### ISSUE TITLE
Floodgate 2.0 update

### ISSUE THREAD

**Issue by Villagers654-zz** [notrhys/BAC#3]

**Comment by Romvnly-Gaming** [comment]
Very descriptive for the author. Now he knows he should be updating his project to Floodgate 2.0 as Floodgate 1.0 is deprecated now and support for it has ceased. Not to mention, Geyser doesn't work with 1.8 anymore. It supports 1.12 - 1.17 with ViaVersion for java clients but for bedrock, they're considered 1.17.
https://github.com/GeyserMC/Floodgate/wiki/Setup-and-Usage#How-do-I-migrate-from-Floodgate-1.0-to-Floodgate-2.0

**Comment by Boryte** [comment]
> Very descriptive for the author. Now he knows he should be updating his project to Floodgate 2.0 as Floodgate 1.0 is deprecated now and support for it has ceased. Not to mention, Geyser doesn't work with 1.8 anymore. It supports 1.12 - 1.17 with ViaVersion for java clients but for bedrock, they're considered 1.17. https://github.com/GeyserMC/Floodgate/wiki/Setup-and-Usage#How-do-I-migrate-from-Floodgate-1.0-to-Floodgate-2.0

Geyser isn't needed to be supported that much since Floodgate is the main thing u are working with when u are working with anticheats.
I have Geyser installed on bungee and only floodgate installed on my backend server. So yes, this anticheat doesn't work as of right now with Geyser installed on Bungeecord and Floodgate 2.0. At least on my test server.

**Comment by Romvnly-Gaming** [comment]
Yeah, it doesn't work on pure Spigot unless you use a proxy.
